// circuito para loggin en giep
const datos = require("../../../fixtures/datosCa/datos-campos.json"); 

class campos{
    campos_usuario(){
        cy.get('.MuiIconButton-colorSecondary').click()
        cy.contains("Campo").click()
        cy.get(':nth-child(2) > .MuiTableCell-alignCenter > .MuiBox-root > [aria-label="Nuevo perfil"] > [data-testid="NoteAddOutlinedIcon"] > path').click().as("nueva historia")
        cy.get('#FechaVisita').click().type("2023-08-08")
        cy.get('#CantidadHa').type(datos.cantHectareas)
        cy.get('#CantidadCabezas').type(datos.cantCabezas)
        cy.get(':nth-child(1) > .MuiButtonBase-root > .PrivateSwitchBase-input').click().as("ciclo recria")
        cy.get('.MuiSwitch-root > .MuiButtonBase-root > .PrivateSwitchBase-input').click().as("cultivos")
        cy.get('.MuiButton-sizeMedium').click({force:true}).as("guardar")
        cy.wait(4000)
        cy.contains('Siguiente').click({force:true}).as("siguiente")

        cy.log("ciclo de recria !")
        cy.get(':nth-child(1) > :nth-child(2) > :nth-child(1) > .MuiButtonBase-root > .PrivateSwitchBase-input').click().as("tipo servicio")
        cy.get(':nth-child(1) > [style="display: flex; flex-direction: row; flex-grow: 1; justify-content: space-between;"] > :nth-child(2) > .MuiButtonBase-root > .PrivateSwitchBase-input').click().as("epoca paricion")
        cy.get('#PorcentajePrenez').click().type(datos.porcentaje)
        cy.get(':nth-child(2) > .MuiFormGroup-root > :nth-child(1) > .MuiButtonBase-root > .PrivateSwitchBase-input').click().as("cultivos")
        cy.get('#ObservacionesCicloDeCria').click().type(datos.observaciones)
        cy.contains('Guardar').click({force:true})
        cy.wait(4000)
        cy.get('.css-1idn90j-MuiGrid-root > .MuiBox-root > :nth-child(3)').click({force:true}).as("siguiente")

        cy.log("formulario de vacas!!!")
        cy.get(':nth-child(1) > :nth-child(2) > :nth-child(1) > .MuiButtonBase-root > .PrivateSwitchBase-input').click().as("alimentacion")
        cy.get(':nth-child(6) > :nth-child(1) > .MuiButtonBase-root > .PrivateSwitchBase-input').click({force:true}).as("sanidad")
        cy.get('#RazaEnParticular').click().type(datos.raza)
        cy.get(':nth-child(2) > :nth-child(2) > :nth-child(1) > .MuiButtonBase-root > .PrivateSwitchBase-input').click().as("vitaminas y minerales")
        cy.get(':nth-child(2) > :nth-child(2) > :nth-child(1) > .MuiButtonBase-root > .PrivateSwitchBase-input').click().as("restriccion alimentaria")
        cy.get('#ObservacionesVaca').click().type(datos.observaciones)
        cy.contains('Guardar').click({force:true})
        cy.wait(4000)
        cy.get('.css-1idn90j-MuiGrid-root > .MuiBox-root > :nth-child(3)').click({force:true}).as("siguiente")

        cy.log("formulario de vaquillonas !!!!")
        cy.get(':nth-child(1) > .MuiButtonBase-root > .PrivateSwitchBase-input').click().as("reposicion")
        cy.get('#EdadServicio').click()
        cy.get('#menu-EdadServicio > .MuiPaper-root > .MuiList-root > [tabindex="0"]').click().as("opcion")
        cy.get('#ObservacionesVaquillona').click().type(datos.observaciones)
        cy.contains('Guardar').click({force:true})
        cy.wait(4000)
        cy.get('.css-1idn90j-MuiGrid-root > .MuiBox-root > :nth-child(3)').click({force:true}).as("siguiente")

        cy.log("formulario de toros !!!")
        cy.get(':nth-child(2) > .MuiFormGroup-root > :nth-child(1) > .MuiButtonBase-root > .PrivateSwitchBase-input').click().as("eleccion toros")
        cy.get('#RazaParticular').click().type(datos.raza)
        cy.get('#ObservacionesToro').click().type(datos.observaciones)
        cy.contains('Guardar').click({force:true})
        cy.wait(4000)
        cy.get('.css-1idn90j-MuiGrid-root > .MuiBox-root > :nth-child(3)').click({force:true}).as("siguiente")

        cy.log("formulario destete !!!!")
        cy.get('#TipoDestete').click()
        cy.get('[data-value="Precoz"]').click().as("tipo destete")
        cy.get('#PorcentajeDestete').click().type(datos.porcentaje)
        cy.get(':nth-child(1) > :nth-child(5) > :nth-child(1) > .MuiButtonBase-root > .PrivateSwitchBase-input').click().as("sanidad")
        cy.get(':nth-child(8) > :nth-child(1) > .MuiButtonBase-root > .PrivateSwitchBase-input').click().as("alimentacion")
        cy.get('#ObservacionesDestete').click().type(datos.observaciones)
        cy.contains('Guardar').click({force:true})
        cy.wait(4000)
        cy.get('.css-1idn90j-MuiGrid-root > .MuiBox-root > :nth-child(3)').click({force:true}).as("siguiente")

        cy.log("formulario de ciclo de recria !!!!")
        cy.get('#PeriodoRecria').click()
        cy.get('[data-value="larga (mas de un año)"]').click()
        cy.get(':nth-child(1) > .MuiFormGroup-root > :nth-child(2) > .MuiButtonBase-root > .PrivateSwitchBase-input').click().as("pastura")
        cy.get('#AlimentacionRecria').click()
        cy.get('[data-value="Recría a corral y terminación a pasto"]').click()
        cy.get('#ObservacionesCicloDeRecria').click().type(datos.observaciones)
        cy.contains('Guardar').click({force:true})
        cy.wait(4000)
        cy.get('.css-1idn90j-MuiGrid-root > .MuiBox-root > :nth-child(3)').click({force:true}).as("siguiente")

        cy.log("formulario de invernada !!!!")
        cy.get('#Procedencia').click().type(datos.procedencia)
        cy.get(':nth-child(3) > :nth-child(1) > .MuiButtonBase-root > .PrivateSwitchBase-input').click().as("compra")
        cy.get(':nth-child(9) > :nth-child(1) > .MuiButtonBase-root > .PrivateSwitchBase-input').click().as("peso")
        cy.get(':nth-child(2) > .MuiFormGroup-root > :nth-child(1) > .MuiButtonBase-root > .PrivateSwitchBase-input').click().as("alimentacion")
        cy.get('#ObservacionesInvernada').click().type(datos.observaciones)
        cy.contains('Guardar').click({force:true})
        cy.wait(4000)
        cy.get('.css-1idn90j-MuiGrid-root > .MuiBox-root > :nth-child(3)').click({force:true}).as("siguiente")

        cy.log("formulario de alimentacion-recria !!!!")
        cy.get(':nth-child(1) > :nth-child(2) > :nth-child(1) > .MuiButtonBase-root > .PrivateSwitchBase-input').click().as("pasturas")
        cy.get('.MuiSwitch-root > .MuiButtonBase-root > .PrivateSwitchBase-input').click().as("granos")
        cy.wait(4000)
        //cy.get('#DiasEncierreRecria').click({force: true} ).type(datos.porcentaje)
        cy.get('#ComposicionDietaRecria').click().type(datos.porcentaje)
        cy.get('#ObservacionesAlimentacionRecria').click().type(datos.observaciones)
        cy.contains('Guardar').click({force:true})
        cy.wait(4000)
        cy.get('.css-1idn90j-MuiGrid-root > .MuiBox-root > :nth-child(3)').click({force:true}).as("siguiente")


        cy.log("formulario de alimentacion-terminacion !!")
        cy.get(':nth-child(2) > :nth-child(4) > .MuiButtonBase-root > .PrivateSwitchBase-input').click().as("pasturas")
        cy.get('.MuiSwitch-root > .MuiButtonBase-root > .PrivateSwitchBase-input').click().as("granos")
        //cy.get('#DiasEncierreTerminacion').click().type(datos.porcentaje)
        cy.get('#ComposicionDietaTerminacion').click().type(datos.porcentaje)
        cy.get('#ObservacionesAlimentacionTerminacion').click().type(datos.observaciones)
        cy.contains('Guardar').click({force:true})
        cy.wait(4000)
        cy.get('.css-1idn90j-MuiGrid-root > .MuiBox-root > :nth-child(3)').click({force:true}).as("siguiente")

        cy.log("formulario opcional ! ")
        cy.get('#AlimentoAdicionalGanado').click().type(datos.observaciones)
        cy.get('#DispuestoAPagarPor').click().type(datos.cantHectareas)
        cy.get('#ServiciosInteres').click().type(datos.cantHectareas)
        cy.get(':nth-child(3) > .MuiButtonBase-root > .PrivateSwitchBase-input').click().as("tipo perfil")
        cy.get('#ObservacionesOpcional').click().type(datos.observaciones)
        cy.contains('Guardar').click({force:true})
        cy.wait(4000)


    }  
}
export default campos; // exportamos clase a archivo de test