 //rcuito para crear una ficha tecnicas en giep

const dataFicha = require("../../fixtures/datosGiep/datos-ficha-tecnica.json");

class fichasTecnicas{
    userCreatFicha(){
      cy.wait(9000)
      
      cy.log("Vamos a ir a fichas Tecnicas")
      cy.wait(2000) 
      cy.get('#menu-item-3 > .mat-button-wrapper > .menu-title').click().as("fichas tecnicas")
      cy.wait(2000) 
      cy.get('.m-1').click().as("boton nueva ficha") 
      cy.wait(9000)
      cy.get("#cliente").type(dataFicha.cliente).debug()
      cy.get('#nombredelProducto').type(dataFicha.producto).debug()
      cy.get('#nombreingles').type(dataFicha.ingles).debug()
      cy.get('#nombreitaliano').type(dataFicha.italiano).debug()
      cy.get('#nombreportugues').type(dataFicha.portugues).debug()
      cy.get("#nombrealeman").type(dataFicha.aleman).debug()
      cy.get("#denominacion").type(dataFicha.denominacion).debug()
      cy.get('#vencimiento').type(dataFicha.vencimineto).debug()
      cy.get('#calidadCorte').type(dataFicha.calidadCorte).debug()
      cy.get('#nombrePideCliente').type(dataFicha.nombrePideCliente).debug()
      cy.get('#descripcionProcesoProductivo').type(dataFicha.descripcionProcesoProductivo).debug()
      cy.get('#packaging').type(dataFicha.packaging).debug()
      cy.get('#materiaprima').type(dataFicha.materiaPrima).debug()
      cy.get('#observaciones').type(dataFicha.observaciones).debug()
      cy.get('#mat-expansion-panel-header-17').click().as("form datos generales")
      cy.get('#codigoarticulo').click().type(dataFicha.codigoArticulo)
      cy.get('#codigoarticulogastro').click().type(dataFicha.codigoArticuloRegistro)
      cy.get('#setnro').click().type(dataFicha.setNro)
      cy.get('#epnro').click().type(dataFicha.epnNro)
      cy.get('#registrocapa').click().type(dataFicha.registroCapa)
      cy.get('#registrodipoa').click().type(dataFicha.registroDiopa)
      cy.get('#consistenteseleccion').click().type(dataFicha.concistenciaSeleccion)
      cy.get('#familia').click().type(dataFicha.familia)
      cy.log("Pasamos a elegir nuestas fechas !!!")
      cy.get(':nth-child(4) > .mat-form-field > .mat-form-field-wrapper > .mat-form-field-flex > .mat-form-field-suffix > .mat-datepicker-toggle > .mat-focus-indicator')
      .click().as("selecciona fecha validez")
      cy.get(':nth-child(5) > [data-mat-col="5"]').click().as("Elegimos una fecha !")
      cy.log("-------------------------------------------")
      cy.get(':nth-child(5) > .mat-form-field > .mat-form-field-wrapper > .mat-form-field-flex > .mat-form-field-suffix > .mat-datepicker-toggle > .mat-focus-indicator')
      .click().as("selecciona fecha emision")
      cy.get(':nth-child(5) > [data-mat-col="2"]').click().as("Elegimos una fecha !")
      cy.log("-------------------------------------------")
      cy.get(':nth-child(6) > .mat-form-field > .mat-form-field-wrapper > .mat-form-field-flex > .mat-form-field-suffix > .mat-datepicker-toggle > .mat-focus-indicator')
      .click().as("selecciona fecha vigencia")
      cy.get(':nth-child(5) > [data-mat-col="4"]').click().as("seleccionamos una fecha")
      cy.log("-------------------------------------------")
      cy.get('#cdk-accordion-child-17 > .mat-expansion-panel-body > :nth-child(1) > :nth-child(9) > .mat-form-field > .mat-form-field-wrapper > .mat-form-field-flex > .mat-form-field-infix')
      .click().as("marca")
      cy.get('#mat-option-30').click().as("opcion")
      cy.get('#cdk-accordion-child-17 > .mat-expansion-panel-body > :nth-child(1) > :nth-child(10) > .mat-form-field > .mat-form-field-wrapper > .mat-form-field-flex > .mat-form-field-infix')
      .click().as("Destino")
      cy.get('#mat-option-39').click().as("opcion destino")
      cy.get('.text-right > .mat-warn').click({force:true}).as("botonGuardar").debug()
      cy.wait(5000)
    }  
    changedEstados(){
      cy.wait(9000)
      cy.contains("Estados").click()
      cy.wait(1000)
      cy.get(':nth-child(1) > .mat-form-field > .mat-form-field-wrapper > .mat-form-field-flex > .mat-form-field-infix').click()
      cy.wait(1000)
      cy.get('#mat-option-0').click().as("Para ingresar")
      cy.get('.flex-p > .mat-accent').click().as("Boton Guardar")
      cy.wait(5000)
      cy.get(':nth-child(1) > .mat-form-field > .mat-form-field-wrapper > .mat-form-field-flex > .mat-form-field-infix')
      .click().as("estado auditar")
      cy.contains('Para auditar').click().as("estado auditar")
      cy.get('.flex-p > .mat-accent').click().as("Boton Guardar")
      cy.wait(5000)

      cy.log("SECCION AUDTIAR !")
      cy.get(':nth-child(1) > .mat-form-field > .mat-form-field-wrapper > .mat-form-field-flex > .mat-form-field-infix')
      .click()
      cy.contains('Para verificar').click()
      cy.wait(3000)
      cy.get('.flex-p > .mat-accent').click().as("Boton guardar")

      cy.log("SECCION VERIFICAR !")
      cy.get(':nth-child(1) > .mat-form-field > .mat-form-field-wrapper > .mat-form-field-flex > .mat-form-field-infix')
      .click()
      cy.wait(3000)
      cy.get(':nth-child(1) > .mat-form-field > .mat-form-field-wrapper > .mat-form-field-flex > .mat-form-field-infix').click()
      cy.contains('Para aprobar').click()
      cy.wait(3000)
      cy.get('.flex-p > .mat-accent').click().as("Boton guardar")

    }
}
export default fichasTecnicas;